openapi: 3.0.1
info:
  title: Data Engineering PoC API
  description: ""
  termsOfService: ""
  contact:
    email: demo@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://example.com/v1
- url: http://example.com/v1
security:
- basicAuth: []
paths:
  /process/{runDateId}:
    get:
      summary: Return count for a specific run date ID
      parameters:
      - name: runDateId
        in: path
        description: Specific run date ID
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Count'
        405:
          description: Invalid input
          content: {}
  /process:
    get:
      summary: Return count of values between two run date IDs
      parameters:
      - name: start
        in: query
        description: Starting run date ID
        required: true
        schema:
          type: string
      - name: end
        in: query
        description: Ending run date ID
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Count'
        405:
          description: Invalid input
          content: {}
components:
  schemas:
    Count:
      type: object
      properties:
        total:
          type: integer
          format: int64
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
