swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Data Engineering PoC API"
  termsOfService: ""
  contact:
    email: "demo@example.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "example.com"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /process/{runDateId}:
    get:
      summary: "Return count for a specific run date ID"
      parameters:
      - name: "runDateId"
        in: "path"
        description: "Specific run date ID"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: '#/definitions/Count'
        "405":
          description: "Invalid input"
  /process:
    get:
      summary: "Return count of values between two run date IDs"
      parameters:
      - name: "start"
        in: "query"
        description: "Starting run date ID"
        required: true
        type: "string"
      - name: "end"
        in: "query"
        description: "Ending run date ID"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: '#/definitions/Count'
        "405":
          description: "Invalid input"
definitions:
  Count:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      runDateId:
        type: "integer"
        format: "int64"
      total:
        type: "integer"
        format: "int64"
