/*
 * Data Engineering Poc
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: demo@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
 package swagger

 type Count struct {
 
	 Id int64 `json:"id,omitempty"`
 
	 RunDateId int64 `json:"runDateId,omitempty"`
 
	 Total int64 `json:"total,omitempty"`
 }
 