openapi: 3.0.1
info:
  title: Data Engineering Poc
  contact:
    email: demo@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://example.com/v1
- url: http://example.com/v1
security:
- basicAuth: []
paths:
  /process/count/{runDateId}:
    get:
      summary: Return count for a specific run date ID
      parameters:
      - name: runDateId
        in: path
        description: Specific run date ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Count'
        "405":
          description: Invalid input
          content: {}
  /process/count:
    get:
      summary: Return count of values between two run date IDs
      parameters:
      - name: start
        in: query
        description: Starting run date ID
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: end
        in: query
        description: Ending run date ID
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Count'
        "405":
          description: Invalid input
          content: {}
components:
  schemas:
    Count:
      type: object
      properties:
        id:
          type: integer
          format: int64
        runDateId:
          type: integer
          format: int64
        total:
          type: integer
          format: int64
      example:
        total: 1
        runDateId: 6
        id: 0
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
